### ISSUE TITLE
Checkbox manual check

### ISSUE THREAD

**Issue by AloysiusParedes** [Intelliabb/XamarinControls#21]
Everything works really well. But I can't find a way to manually set the checkbox's "checked" status via code. There's the function to check if the checkbox is checked (returns bool), but not manual setting.

Is there a function to set the check box to "checked" or "unchecked"?

i.e. myCheckBox.SetChecked(true);

**Comment by Intelliabb** [comment]
You can set the check directly as,
`myCheckBox.IsChecked = true;`

**Comment by AloysiusParedes** [comment]
> You can set the check directly as,
> `myCheckBox.IsChecked = true;`

*face palm* hahaha I guess my brain isn't functioning very well at the moment. Thank you so much!! That worked :)
